//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deposit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardHistory
    {
        public int Id { get; set; }
        public string IdCard { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Desription { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
