//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Deposit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposits
    {
        [Key]
        public int Id { get; set; }

        public decimal InitialAmount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Name { get; set; }
    
        public virtual DepositOwnership DepositOwnership { get; set; }
        public virtual DepositStates DepositStates { get; set; }
        public virtual DepositTerms DepositTerms { get; set; }
    }
}
