//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Deposit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositOwnership
    {
        public string UserId { get; set; }

        [Key]
        public int DepositId { get; set; }

        public string info { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Deposits Deposits { get; set; }
    }
}
