//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deposit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepositEntities : DbContext
    {
        public DepositEntities()
            : base("name=DepositEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CardHistory> CardHistory { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Deposits> Deposits { get; set; }
        public virtual DbSet<DepositStates> DepositStates { get; set; }
        public virtual DbSet<DepositTerms> DepositTerms { get; set; }
    }
}
