//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deposit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositStates
    {
        public DepositStates()
        {
            this.Deposits = new HashSet<Deposits>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Deposits> Deposits { get; set; }
    }
}
