//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DepositDatabase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public Cards()
        {
            this.CardHistory = new HashSet<CardHistory>();
            this.Deposits = new HashSet<Deposits>();
        }
    
        public string Id { get; set; }
        public string UserOwnerId { get; set; }

        [Display(Name = "Expiration month")]
        public string ExpirationMonth { get; set; }

        [Display(Name = "Expiration year")]
        public string ExpirationYear { get; set; }

        [Display(Name = "Secret code")]
        public string SecretCode { get; set; }

        public byte CurrencyId { get; set; }
        
        [Display(Name = "Balance")]
        public decimal Balance { get; set; }
        
        [Display(Name = "Owner")]
        public virtual AspNetUsers AspNetUsers { get; set; }

        public virtual ICollection<CardHistory> CardHistory { get; set; }

        [Display(Name = "Currency")]
        public virtual Currencies Currencies { get; set; }

        public virtual ICollection<Deposits> Deposits { get; set; }
    }
}
