//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DepositDatabase.Model
{
    public partial class CardHistory
    {
        public int Id { get; set; }
        public string IdCard { get; set; }
        public DateTime DateTime { get; set; }
        public string Desription { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
