//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DepositDatabase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.Cards = new HashSet<Cards>();
            this.DepositTerms = new HashSet<DepositTerms>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public byte Id { get; set; }
        
        [Display(Name = "Currency")]
        public string Name { get; set; }

        [Display(Name = "Currency")]
        public string Abbreviation { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<DepositTerms> DepositTerms { get; set; }
    }
}
