//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepositDatabase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositTerms
    {
        public DepositTerms()
        {
            this.Deposits = new HashSet<Deposits>();
        }
    
        public byte Id { get; set; }
        public byte CurrencyId { get; set; }
        public byte Months { get; set; }
        public decimal InterestRate { get; set; }
        public string Name { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual ICollection<Deposits> Deposits { get; set; }
    }
}
