//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DepositDatabase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposits
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        public string UserOwnerId { get; set; }
        public byte TermId { get; set; }

        [Display(Name = "Initial amount")]
        public decimal InitialAmount { get; set; }

        [Display(Name = "Balance")]
        public decimal Balance { get; set; }

        [Display(Name = "Start date")]
        public System.DateTime StartDate { get; set; }

        [Display(Name = "End date")]
        public System.DateTime EndDate { get; set; }


        [Display(Name = "Last interest payment date")]
        public Nullable<System.DateTime> LastInterestPaymentDate { get; set; }

        public byte StateId { get; set; }
        public byte WayOfAccumulationId { get; set; }
        public string CardForAccumulationId { get; set; }

        [Display(Name = "Deposit name")]
        public string Name { get; set; }

        [Display(Name = "Owner")]
        public virtual AspNetUsers AspNetUsers { get; set; }

        [Display(Name = "Card for accumulation")]
        public virtual Cards Cards { get; set; }

        [Display(Name = "State")]
        public virtual DepositStates DepositStates { get; set; }

        [Display(Name = "Deposit terms")]
        public virtual DepositTerms DepositTerms { get; set; }

        [Display(Name = "Way of accumulation")]
        public virtual DepositWaysOfAccumulation DepositWaysOfAccumulation { get; set; }
    }
}
